// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AmbientState {
    /**
     * Creates a new AmbientState instance.
     * @param {Partial<AmbientState>} [$$source = {}] - The source object to create the AmbientState.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mode"] = 0;
        }
        if (!("ambientRaw" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ambientRaw"] = 0;
        }
        if (!("ambientPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ambientPercent"] = 0;
        }
        if (!("voiceFocus" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["voiceFocus"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AmbientState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AmbientState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AmbientState(/** @type {Partial<AmbientState>} */($$parsedSource));
    }
}

export class BatteryCell {
    /**
     * Creates a new BatteryCell instance.
     * @param {Partial<BatteryCell>} [$$source = {}] - The source object to create the BatteryCell.
     */
    constructor($$source = {}) {
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatteryCell instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatteryCell}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatteryCell(/** @type {Partial<BatteryCell>} */($$parsedSource));
    }
}

export class BatteryState {
    /**
     * Creates a new BatteryState instance.
     * @param {Partial<BatteryState>} [$$source = {}] - The source object to create the BatteryState.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BatteryCell | null | undefined}
             */
            this["headset"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BatteryCell | null | undefined}
             */
            this["left"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BatteryCell | null | undefined}
             */
            this["right"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BatteryCell | null | undefined}
             */
            this["case"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatteryState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatteryState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headset" in $$parsedSource) {
            $$parsedSource["headset"] = $$createField0_0($$parsedSource["headset"]);
        }
        if ("left" in $$parsedSource) {
            $$parsedSource["left"] = $$createField1_0($$parsedSource["left"]);
        }
        if ("right" in $$parsedSource) {
            $$parsedSource["right"] = $$createField2_0($$parsedSource["right"]);
        }
        if ("case" in $$parsedSource) {
            $$parsedSource["case"] = $$createField3_0($$parsedSource["case"]);
        }
        return new BatteryState(/** @type {Partial<BatteryState>} */($$parsedSource));
    }
}

export class DeviceState {
    /**
     * Creates a new DeviceState instance.
     * @param {Partial<DeviceState>} [$$source = {}] - The source object to create the DeviceState.
     */
    constructor($$source = {}) {
        if (!("device" in $$source)) {
            /**
             * @member
             * @type {DeviceSummary}
             */
            this["device"] = (new DeviceSummary());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["modelId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["color"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["serialNumber"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["firmwareRaw"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modelRaw"] = undefined;
        }
        if (!("battery" in $$source)) {
            /**
             * @member
             * @type {BatteryState}
             */
            this["battery"] = (new BatteryState());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VolumeState | null | undefined}
             */
            this["headphoneVolume"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VolumeState | null | undefined}
             */
            this["micVolume"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AmbientState | null | undefined}
             */
            this["ambient"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["gameChatMix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {VolumeState | null | undefined}
             */
            this["sidetone"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["surround"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["btStatus"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["btSoundQuality"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["btStartupMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["autoPowerOff"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["ncStartupMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["connectionMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SimpleState | null | undefined}
             */
            this["assignable"] = undefined;
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType5;
        const $$createField10_0 = $$createType7;
        const $$createField11_0 = $$createType9;
        const $$createField12_0 = $$createType5;
        const $$createField13_0 = $$createType9;
        const $$createField14_0 = $$createType9;
        const $$createField15_0 = $$createType9;
        const $$createField16_0 = $$createType9;
        const $$createField17_0 = $$createType9;
        const $$createField18_0 = $$createType9;
        const $$createField19_0 = $$createType9;
        const $$createField20_0 = $$createType9;
        const $$createField21_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("device" in $$parsedSource) {
            $$parsedSource["device"] = $$createField0_0($$parsedSource["device"]);
        }
        if ("battery" in $$parsedSource) {
            $$parsedSource["battery"] = $$createField7_0($$parsedSource["battery"]);
        }
        if ("headphoneVolume" in $$parsedSource) {
            $$parsedSource["headphoneVolume"] = $$createField8_0($$parsedSource["headphoneVolume"]);
        }
        if ("micVolume" in $$parsedSource) {
            $$parsedSource["micVolume"] = $$createField9_0($$parsedSource["micVolume"]);
        }
        if ("ambient" in $$parsedSource) {
            $$parsedSource["ambient"] = $$createField10_0($$parsedSource["ambient"]);
        }
        if ("gameChatMix" in $$parsedSource) {
            $$parsedSource["gameChatMix"] = $$createField11_0($$parsedSource["gameChatMix"]);
        }
        if ("sidetone" in $$parsedSource) {
            $$parsedSource["sidetone"] = $$createField12_0($$parsedSource["sidetone"]);
        }
        if ("surround" in $$parsedSource) {
            $$parsedSource["surround"] = $$createField13_0($$parsedSource["surround"]);
        }
        if ("btStatus" in $$parsedSource) {
            $$parsedSource["btStatus"] = $$createField14_0($$parsedSource["btStatus"]);
        }
        if ("btSoundQuality" in $$parsedSource) {
            $$parsedSource["btSoundQuality"] = $$createField15_0($$parsedSource["btSoundQuality"]);
        }
        if ("btStartupMode" in $$parsedSource) {
            $$parsedSource["btStartupMode"] = $$createField16_0($$parsedSource["btStartupMode"]);
        }
        if ("autoPowerOff" in $$parsedSource) {
            $$parsedSource["autoPowerOff"] = $$createField17_0($$parsedSource["autoPowerOff"]);
        }
        if ("ncStartupMode" in $$parsedSource) {
            $$parsedSource["ncStartupMode"] = $$createField18_0($$parsedSource["ncStartupMode"]);
        }
        if ("connectionMode" in $$parsedSource) {
            $$parsedSource["connectionMode"] = $$createField19_0($$parsedSource["connectionMode"]);
        }
        if ("assignable" in $$parsedSource) {
            $$parsedSource["assignable"] = $$createField20_0($$parsedSource["assignable"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField21_0($$parsedSource["warnings"]);
        }
        return new DeviceState(/** @type {Partial<DeviceState>} */($$parsedSource));
    }
}

export class DeviceSummary {
    /**
     * Creates a new DeviceSummary instance.
     * @param {Partial<DeviceSummary>} [$$source = {}] - The source object to create the DeviceSummary.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("product" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["product"] = "";
        }
        if (!("manufacturer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["manufacturer"] = "";
        }
        if (!("serial" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serial"] = "";
        }
        if (!("vendorId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vendorId"] = 0;
        }
        if (!("productId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["productId"] = 0;
        }
        if (!("usagePage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usagePage"] = 0;
        }
        if (!("usage" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["usage"] = 0;
        }
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interface"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("isBuds" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isBuds"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceSummary(/** @type {Partial<DeviceSummary>} */($$parsedSource));
    }
}

export class FeatureStatus {
    /**
     * Creates a new FeatureStatus instance.
     * @param {Partial<FeatureStatus>} [$$source = {}] - The source object to create the FeatureStatus.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FeatureStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FeatureStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FeatureStatus(/** @type {Partial<FeatureStatus>} */($$parsedSource));
    }
}

export class SimpleState {
    /**
     * Creates a new SimpleState instance.
     * @param {Partial<SimpleState>} [$$source = {}] - The source object to create the SimpleState.
     */
    constructor($$source = {}) {
        if (!("eventId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["eventId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["value"] = undefined;
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["raw"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SimpleState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SimpleState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("raw" in $$parsedSource) {
            $$parsedSource["raw"] = $$createField2_0($$parsedSource["raw"]);
        }
        return new SimpleState(/** @type {Partial<SimpleState>} */($$parsedSource));
    }
}

export class VolumeState {
    /**
     * Creates a new VolumeState instance.
     * @param {Partial<VolumeState>} [$$source = {}] - The source object to create the VolumeState.
     */
    constructor($$source = {}) {
        if (!("mute" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mute"] = 0;
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["raw"] = 0;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VolumeState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VolumeState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VolumeState(/** @type {Partial<VolumeState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BatteryCell.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = DeviceSummary.createFrom;
const $$createType3 = BatteryState.createFrom;
const $$createType4 = VolumeState.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = AmbientState.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = SimpleState.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = $Create.Array($Create.Any);
