// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.FeatureStatus[]>}
 */
export function FeatureMatrix() {
    return $Call.ByID(1346072470).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<$models.DeviceState | null>}
 */
export function GetDeviceState(index) {
    return $Call.ByID(2939368488, index).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.DeviceSummary[]>}
 */
export function ListDevices() {
    return $Call.ByID(2495038762).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RepairUdevPermissions() {
    return $Call.ByID(3584598172);
}

/**
 * @param {number} index
 * @param {number} mode
 * @param {number} level
 * @param {boolean} voiceFocus
 * @returns {$CancellablePromise<void>}
 */
export function SetAmbient(index, mode, level, voiceFocus) {
    return $Call.ByID(656779707, index, mode, level, voiceFocus);
}

/**
 * @param {number} index
 * @param {number} slot
 * @param {number} action
 * @returns {$CancellablePromise<void>}
 */
export function SetAssignableAction(index, slot, action) {
    return $Call.ByID(3507214662, index, slot, action);
}

/**
 * @param {number} index
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoPowerOff(index, minutes) {
    return $Call.ByID(3227335332, index, minutes);
}

/**
 * @param {number} index
 * @param {number} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetBTSoundQuality(index, mode) {
    return $Call.ByID(4008264479, index, mode);
}

/**
 * @param {number} index
 * @param {number} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetBTStartupMode(index, mode) {
    return $Call.ByID(1451227367, index, mode);
}

/**
 * @param {number} index
 * @param {number} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetConnectionDestinationMode(index, mode) {
    return $Call.ByID(3314670188, index, mode);
}

/**
 * @param {number} index
 * @param {number} balance
 * @returns {$CancellablePromise<void>}
 */
export function SetGameChatMix(index, balance) {
    return $Call.ByID(1253652645, index, balance);
}

/**
 * @param {number} index
 * @param {number} percent
 * @returns {$CancellablePromise<void>}
 */
export function SetHeadphoneVolume(index, percent) {
    return $Call.ByID(1319266955, index, percent);
}

/**
 * @param {number} index
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetIncomingPermission(index, enabled) {
    return $Call.ByID(899379606, index, enabled);
}

/**
 * @param {number} index
 * @param {number} percent
 * @returns {$CancellablePromise<void>}
 */
export function SetMicVolume(index, percent) {
    return $Call.ByID(1066111170, index, percent);
}

/**
 * @param {number} index
 * @param {number} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetNCStartupMode(index, mode) {
    return $Call.ByID(1534465444, index, mode);
}

/**
 * @param {number} index
 * @param {number} percent
 * @returns {$CancellablePromise<void>}
 */
export function SetSidetone(index, percent) {
    return $Call.ByID(682424358, index, percent);
}

/**
 * @param {number} index
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetSurround(index, enabled) {
    return $Call.ByID(2691789515, index, enabled);
}

// Private type creation functions
const $$createType0 = $models.FeatureStatus.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.DeviceState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.DeviceSummary.createFrom;
const $$createType5 = $Create.Array($$createType4);
