PACKAGE_NAME="hid-inzone-battery"
PACKAGE_VERSION="0.1.12"
BUILT_MODULE_NAME[0]="hid_inzone_battery"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hid"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
